version: '3.8'

services:
  facial-recognition-app:
    build: .
    container_name: face_recognition_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      # Dossier pour stocker tes modèles (poids ArcFace, YOLO, etc.) pour éviter de les retélécharger à chaque redémarrage
      - ./models:/app/models
      # Dossier pour tes visages connus ou ta base de données si elle utilise des fichiers locaux
      - ./known_faces:/app/known_faces
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # Alloue automatiquement ta carte graphique détectée
              capabilities: [gpu]