services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    volumes:
      - ./qdrant_storage:/qdrant/storage

  facial-recognition-app:
    build: .
    container_name: face_recognition_api
    restart: always
    ports:
    - "8000:8000"
    environment:
      - qdrant_host=qdrant
      - Qdrant_port=6333
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  mon-site-web:
    image: php:8.2-apache
    container_name: site_web_php
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./siteWeb:/var/www/html/
      - ./ssl.conf:/etc/apache2/sites-enabled/ssl.conf
      - /home/ub_admin/certs/server.crt:/etc/ssl/certs/server.crt
      - /home/ub_admin/certs/server.key:/etc/ssl/private/server.key
    command: bash -c "a2enmod ssl && apache2-foreground"
    depends_on:
      - facial-recognition-app
